# Generated by Django 4.2.1 on 2023-06-12 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('country', models.CharField(max_length=45, verbose_name='Country')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('district', models.CharField(max_length=55, verbose_name='district')),
                ('address_line1', models.CharField(max_length=45, verbose_name='Address line 1')),
                ('address_line2', models.CharField(blank=True, default='', max_length=45, verbose_name='Address line 2')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal code')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('timezone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Timezone')),
                ('first_name', models.CharField(max_length=45, verbose_name='First name')),
                ('last_name', models.CharField(max_length=45, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('speciality', models.CharField(max_length=45, verbose_name='Speciality')),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consultation fee')),
                ('membership_exclusive_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Membership exclusive price')),
                ('language', models.CharField(choices=[('English', 'English'), ('French', 'French'), ('German', 'German'), ('Spanish', 'Spanish'), ('Italian', 'Italian'), ('Russian', 'Russian'), ('Chinese', 'Chinese')], max_length=45, verbose_name='Languages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15, verbose_name='Day')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='Schedule')),
            ],
            options={
                'verbose_name': 'Doctor schedule',
                'verbose_name_plural': 'Doctor schedules',
            },
        ),
    ]
